AddTarget(NAME ImageKitUI
    SOURCE_DIR
        ${SOURCE_ROOT}/Application/ImageKitUI/
    SRC
        *.cpp
        *.h
        *.qrc
    UI_FILES
        ${SOURCE_DIR}/*.ui
        ${SOURCE_DIR}/UI/*.ui
        ${SOURCE_DIR}/UI/Scene/*.ui
    SUBDIRS
    	Engine/
    	UI/
        UI/Scene/
    DEPS
        ImageCore
        ImageKitEffects
    QT_USE
        Core
        Widgets
)